---
title: "The Gap: The Effect of Race and The Pandemic on CPS Learning"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Lily Ng"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---
```{r}
# load packages and data
library(tidyverse)
library(janitor)
library(naniar)
library(gt)

cps <- read_rds("data/cps_data.rds")
```

::: {.callout-tip icon="false"}
## Github Repo Link

[Final Project Github Repo](https://github.com/stat301-1-2023-fall/final-project-1-lilyng3)
:::

## Introduction

## Data overview & quality

## Explorations

```{r}
# data manipulation
racial_groups <- c("student_count_black", "student_count_hispanic", "student_count_white", "student_count_asian", "student_count_native_american", "student_count_other_ethnicity","student_count_asian_pacific_islander", "student_count_multi", "student_count_hawaiian_pacific_islander", "student_count_ethnicity_not_available")

ela_score <- c("percent_did_not_meet_ela", "percent_partially_met_ela", "percent_approached_ela", "percent_met_ela", "percent_exceeded_ela", "percent_met_or_exceeded_ela")

math_score <- c("percent_did_not_meet_math", "percent_partially_met_math", "percent_approached_math", "percent_met_math", "percent_exceeded_math", "percent_met_or_exceeded_math")

cps_sorted <- cps |> 
  mutate(
    primary_race = apply(cps[, racial_groups], 1, function(row) {
      names(row)[which.max(row)]}),
    primary_ela = names(cps[, ela_score])[max.col(cps[, ela_score], "last")],
    primary_math = names(cps[, math_score])[max.col(cps[, math_score], "last")]
  ) |> 
  mutate(primary_race = sub("student_count_", "", primary_race),
         percent_low_income = round((student_count_low_income / student_count_total) * 100, 1),
         title_one = percent_low_income >= 40) |>
  filter(school_name != "U OF C - WOODLAWN HS") |> 
  mutate(
    primary_race = factor(primary_race),
    primary_ela = factor(primary_ela),
    primary_math = factor(primary_math)
  )

# ela and math
pandemic_scores <- cps |> 
  group_by(year) |> 
  summarise(
    avg_met_exceeded_ela = mean(percent_met_or_exceeded_ela, na.rm = TRUE),
    avg_met_exceeded_math = mean(percent_met_or_exceeded_math, na.rm = TRUE),
  )

# by race
pandemic_scores_race <- cps_sorted |> 
  group_by(year, primary_race) |> 
  summarise(
    avg_met_exceeded_ela = mean(percent_met_or_exceeded_ela, na.rm = TRUE),
    avg_met_exceeded_math = mean(percent_met_or_exceeded_math, na.rm = TRUE)
  )

# by income
pandemic_scores_lowincome <- cps_sorted |>
  filter(title_one == TRUE) |>
  group_by(year) |>
  summarise(
    avg_met_exceeded_ela = mean(percent_met_or_exceeded_ela, na.rm = TRUE),
    avg_met_exceeded_math = mean(percent_met_or_exceeded_math, na.rm = TRUE)
  )

combined_data <-
  merge(pandemic_scores, pandemic_scores_lowincome, by = c("year")) |>
  pivot_longer(
    cols = c("avg_met_exceeded_ela.x", "avg_met_exceeded_ela.y"),
    names_to = "group_ela",
    values_to = "avg_met_exceeded_ela"
  ) |>
  pivot_longer(
    cols = c("avg_met_exceeded_math.x", "avg_met_exceeded_math.y"),
    names_to = "group_math",
    values_to = "avg_met_exceeded_math"
  )

pandemic_scores_race_lowincome <- cps_sorted |>
  filter(title_one == TRUE) |>
  group_by(year, primary_race) |>
  summarise(
    avg_met_exceeded_ela = mean(percent_met_or_exceeded_ela, na.rm = TRUE),
    avg_met_exceeded_math = mean(percent_met_or_exceeded_math, na.rm = TRUE)
  )
```

#### English Language Arts & Math Scores

In @fig-ela, we see 

```{r}
#| label: fig-ela
#| fig-cap: Primary ELA Scores by Year

cps_sorted |> 
  ggplot(aes(x = factor(primary_ela, levels = c("percent_did_not_meet_ela", "percent_partially_met_ela", "percent_approached_ela", "percent_met_or_exceeded_ela")))) + 
  geom_bar(fill = "#F7B4AD") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -0.5, position = position_stack(vjust = 0.5)) +
  labs(
    title = "Primary ELA Scores by Year",
    x = "Primary ELA Score",
    y = "Count"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("% Did Not Meet", "% Partially Met", "% Approached", "% Met or Exceeded")) +
  facet_wrap(~ year)
```

```{r}
#| label: fig-math
#| fig-cap: Primary Math Scores by Year

cps_sorted |> 
  ggplot(aes(x = factor(primary_math, levels = c("percent_did_not_meet_math", "percent_partially_met_math", "percent_approached_math", "percent_met_or_exceeded_math")))) + 
  geom_bar(fill = "#B4CCE3") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -0.5, position = position_stack(vjust = 0.5)) +
  labs(
    title = "Primary Math Scores by Year",
    x = "Primary Math Score",
    y = "Count"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  scale_x_discrete(labels = c("% Did Not Meet", "% Partially Met", "% Approached", "% Met or Exceeded")) +
  facet_wrap(~ year)
```

```{r}
#| label: fig-ela-met
#| fig-cap: Percentage of Students Meeting ELA Levels by Year

# ela scores
ggplot(pandemic_scores, aes(x = as.factor(year), y = avg_met_exceeded_ela)) +
  geom_bar(stat = "identity", position = "dodge", fill = "#F7B4AD") +
  labs(title = "Percentage of Students Meeting ELA Levels by Year",
       x = "Year",
       y = "Average % Met ELA Levels") +
  theme_minimal()
```

```{r}
#| label: fig-math-met
#| fig-cap: Percentage of Students Meeting Math Levels by Year

# math scores
ggplot(pandemic_scores, aes(x = as.factor(year), y = avg_met_exceeded_math)) +
  geom_bar(stat = "identity", position = "dodge", fill = "#B4CCE3") +
  labs(title = "Percentage of Students Meeting Math Levels by Year",
       x = "Year",
       y = "Average % Met Math Levels") +
  theme_minimal()
```

#### Race
```{r}
#| label: fig-race
#| fig-cap: Primary Race of School by Year

cps_sorted |> 
  ggplot(aes(x = "", fill = primary_race)) +
  geom_bar(width = 1) +
  scale_fill_brewer(palette = "Set1", labels = c("Asian", "Black", "Hispanic", "White")) +
  labs(
    title = "Distribution of Primary Race by Year",
    x = NULL,
    y = NULL,
    fill = "Primary Race"
  ) +
  facet_wrap(~ year) +
  coord_polar(theta = "y") +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.title = element_blank(), 
        axis.text = element_blank(),   
        axis.ticks = element_blank(),
        panel.grid = element_blank())
```


```{r}
#| label: fig-race-table
#| fig-cap: Primary Race of School by Year

cps_sorted |> 
  group_by(year, primary_race) |>
  summarise(count = n()) |>
  group_by(year) |>
  mutate(percentage = round(count / sum(count) * 100, 1)) |>
  mutate(primary_race = str_to_title(primary_race)) |>
  gt() |>
  tab_header(
    title = "Primary Race of School by Year",
  ) |>
  cols_label(
    year = "Year",
    primary_race = "Primary Race",
    count = "Count",
    percentage = "Percentage (%)"
  )
```


```{r}
#| label: fig-ela-race
#| fig-cap: Percentage of Students Meeting ELA Levels by Primary Race of School by Year

ggplot(pandemic_scores_race, aes(x = as.factor(year), y = avg_met_exceeded_ela, color = primary_race)) +
  geom_point() +
  geom_line(aes(group = primary_race)) +
  labs(title = "Percentage of Students Meeting ELA Levels by Primary Race of School by Year",
       x = "Year",
       y = "Average % Met ELA Levels",
       color = "Primary Race") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", labels = c("Asian", "Black", "Hispanic", "White")) + 
  theme(legend.position = "bottom")
```

```{r}
#| label: fig-math-race
#| fig-cap: Percentage of Students Meeting Math Levels by Primary Race of School by Year

ggplot(pandemic_scores_race, aes(x = as.factor(year), y = avg_met_exceeded_math, color = primary_race)) +
  geom_point() +
  geom_line(aes(group = primary_race)) +
  labs(title = "Percentage of Students Meeting Math Levels by Primary Race of School by Year",
       x = "Year",
       y = "Average % Met Math Levels",
       color = "Primary Race") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", labels = c("Asian", "Black", "Hispanic", "White")) + 
  theme(legend.position = "bottom")
```

#### Low-Income
```{r}
#| label: fig-low-income
#| fig-cap: Distribution of Low-Income Students

cps_sorted |> 
  ggplot(aes(x = percent_low_income)) +
  geom_histogram(bins = 80, fill = "#E0CBE4") +
  theme_minimal() +
  labs(
    title = "Distribution of Low-Income Students",
    x = "% Low-Income Students Out of Whole Student Body",
    y = "Count"
  )
```

```{r}
#| label: fig-title-one
#| fig-cap: Title 1 Schools by Primary Race

cps_sorted |> 
  filter(title_one == TRUE) |> 
  ggplot(aes(x = primary_race, fill = primary_race)) +
  geom_bar() +
  labs(
    title = "Title 1 Schools by Primary Race",
    x = "Primary Race",
    y = "Count",
    fill = "Primary Race"
  ) +
  scale_fill_brewer(palette = "Set1") +
  scale_x_discrete(labels = c("Asian", "Black", "Hispanic", "White")) +
  theme_minimal()
```

```{r}
#| label: fig-combined-ela
#| fig-cap: Percentage of Students Meeting ELA Levels by Year by Income

ggplot(combined_data,
       aes(x = as.factor(year), y = avg_met_exceeded_ela, fill = group_ela)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Students Meeting ELA Levels by Year by Income",
       x = "Year",
       y = "Average % Met ELA Levels") +
  scale_fill_manual(values = c("#F7B4AD", "#E0CBE4"), name = "Group", labels = c("Average", "Title 1")) +
  theme_minimal()
```

```{r}
#| label: fig-combined-math
#| fig-cap: Percentage of Students Meeting Math Levels by Year by Income

ggplot(combined_data,
       aes(x = as.factor(year), y = avg_met_exceeded_math, fill = group_math)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Students Meeting Math Levels by Year by Income",
       x = "Year",
       y = "Average % Met Math Levels") +
  scale_fill_manual(values = c("#B4CCE3", "#E0CBE4"), name = "Group", labels = c("Average", "Title 1")) +
  theme_minimal()
```

```{r}
#| label: fig-combined-race-ela
#| fig-cap: Percentage of Students Meeting ELA Levels by Primary Race and Income of School by Year

avg_ela <- ggplot(pandemic_scores_race, aes(x = as.factor(year), y = avg_met_exceeded_ela, color = primary_race)) +
  geom_point() +
  geom_line(aes(group = primary_race)) +
  labs(title = "Percentage of Students Meeting ELA Levels by Primary Race and Income of School by Year",
       x = "Year",
       y = "Average % Met ELA Levels",
       color = "Primary Race\n(Title 1 = dashed)") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", labels = c("Asian", "Black", "Hispanic", "White")) + 
  theme(legend.position = "bottom")

avg_ela + 
  geom_point(data = pandemic_scores_race_lowincome, aes(x = as.factor(year), y = avg_met_exceeded_ela, color = primary_race), shape = 1) +
  geom_line(data = pandemic_scores_race_lowincome, aes(x = as.factor(year), y = avg_met_exceeded_ela, group = primary_race), linetype = "dashed")
```

```{r}
#| label: fig-combined-race-math
#| fig-cap: Percentage of Students Meeting Math Levels by Primary Race and Income of School by Year

avg_math <- ggplot(pandemic_scores_race, aes(x = as.factor(year), y = avg_met_exceeded_math, color = primary_race)) +
  geom_point() +
  geom_line(aes(group = primary_race)) +
  labs(title = "Percentage of Students Meeting Math Levels by Primary Race and Income of School by Year",
       x = "Year",
       y = "Average % Met Math Levels",
       color = "Primary Race\n(Title 1 = dashed)") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", labels = c("Asian", "Black", "Hispanic", "White")) + 
  theme(legend.position = "bottom")

avg_math + 
  geom_point(data = pandemic_scores_race_lowincome, aes(x = as.factor(year), y = avg_met_exceeded_math, color = primary_race), shape = 1) +
  geom_line(data = pandemic_scores_race_lowincome, aes(x = as.factor(year), y = avg_met_exceeded_math, group = primary_race), linetype = "dashed")
```


## Conclusion

## References — if needed

## Appendix: technical info — if needed

## Appendix: extra explorations — if needed
